--
-- 시퀀스
-- 시퀀스는 오라클 데이터베이스에서 특정 규칙에 맞는 연속된 숫자를 생성하는 객체이다.

-- 연습용 테이블 생성
CREATE TABLE DEPT_SEQUENCE
    AS SELECT DEPTNO, DNAME, LOC
         FROM DEPT
        WHERE 1 <> 1;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 0
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;
  
-- 생성된 시퀀스 객체 조회  
SELECT *
  FROM USER_SEQUENCES;
  
-- 시퀀스 사용하기
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- 저장된 데이터 조회
SELECT *
  FROM DEPT_SEQUENCE;
  
-- 현재 시퀀스 값 확인하기
SELECT SEQ_DEPT_SEQUENCE.CURRVAL
  FROM DUAL;
  
--
-- 부서명 : DATABASE
-- 지역 : SEOUL
-- 부서번호 90번까지 추가하기
-- [DEPTNO : 20]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 30]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 40]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 50]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 60]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 70]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 80]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- [DEPTNO : 90]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
-- (NOCYCLE 옵션으로 SEQUENCE를 생성했기 때문에, 더이상 생성이 안되고 오류가 발생한다)


--
-- 시퀀스 수정하기
--
-- 시퀀스 수정은 ALTER명령어를 사용한다.
-- START WITH (시작값) 은 수정할 수 없다.
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    MAXVALUE 99
    INCREMENT BY 3
    CYCLE;

-- 수정된 시퀀스 조회하기
SELECT *
  FROM USER_SEQUENCES;
  
-- 데이터 추가하기
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

-- 추가된 데이터 확인
SELECT *
  FROM DEPT_SEQUENCE;
  

--
-- CYCLE 옵션의 동작확인을 위한 데이터 입력
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT *
  FROM DEPT_SEQUENCE;
  
  
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT *
  FROM DEPT_SEQUENCE;
-- MAXVALUE 인 99까지 생성됨

INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT *
  FROM DEPT_SEQUENCE;
-- CYCLE 옵션에 의해, 시작값으로 돌아가서 생성됨

INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT *
  FROM DEPT_SEQUENCE;
  
-- [DEPTNO : 6]
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT *
  FROM DEPT_SEQUENCE;
-- CYCLE 옵션에 의해 계속 순환됨을 알 수 있다.


--
-- 시퀀스 삭제하기
-- 시퀀스는 삭제하더라도, 이 시퀀스를 사용했던 테이블의 데이터는 영향을 받지 않는다
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

-- 시퀀스 삭제 후, 확인하기
SELECT *
  FROM USER_SEQUENCES;