--
-- PRIMARY KEY
-- 해당 열을 기본키로 지정한다.
-- PRIMARY KEY 제약조건은 한 테이블에 하나의 열만 지정할 수 있고,
-- 해당 열은 UNIQUE제약조건 과 NOT NULL제약조건 까지 적용된다.
-- (PRIMARY KEY로 지정된 열은, 자동으로 인덱스가 생성된다)

-- PRIMARY KEY 제약조건을 지정하여 테이블 생성하기
CREATE TABLE TABLE_PK(
    LOGIN_ID        VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD       VARCHAR2(20) NOT NULL,
    TEL             VARCHAR2(20)
);

-- 생성한 테이블의 제약조건 뷰 조회하기
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_PK';
 
-- 생성한 테이블의 PRIMARY KEY 열의 인덱스 뷰 조회하기
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME
  FROM USER_INDEXES
 WHERE TABLE_NAME LIKE 'TABLE_PK%';
 
 
-- 테이블 생성시 PRIMARY KEY 제약조건 이름 지정하여 생성하기
CREATE TABLE TABLE_PK2(
    LOGIN_ID        VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD       VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
    TEL             VARCHAR2(20)
);

-- 생성한 테이블의 제약조건 뷰 조회하기
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_PK2';

-- 생성한 테이블의 인덱스 조회하기
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME
  FROM USER_INDEXES
 WHERE TABLE_NAME LIKE 'TABLE_PK%';
 

-- PRIMARY KEY 열에 중복값 입력 테스트 하기
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-1234');

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD02', '010-1234-5678');

-- PRIMARY KEY 열에 NULL값 입력 테스트 하기
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD02', '010-1234-1234');

-- PRIMARY KEY 제약조건 이름 변경하기
ALTER TABLE TABLE_PK2
RENAME CONSTRAINT TBLPK2_LGNID_PK TO PPP;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME LIKE 'TABLE_PK%';
 

-- CREATE문에 아웃오브라인(Out of line) 또는 테이블레벨(Table level) 제약조건 정의 하기
CREATE TABLE TABLE_PK3(
    LOGIN_ID        VARCHAR2(20),
    LOGIN_PWD       VARCHAR2(20) NOT NULL,
    TEL             VARCHAR2(20),
    PRIMARY KEY(LOGIN_ID),
    CONSTRAINT CONSTRAINT_TEL_UNIQUE UNIQUE(TEL)
);

SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_PK3';