--
-- 제약조건 연습문제

-- [1] DEPT_CONST 테이블과 EMP_CONST 테이블을 조건에 맞게 생성하기
CREATE TABLE DEPT_CONST(
    DEPTNO      NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME       VARCHAR(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC         VARCHAR(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);

CREATE TABLE EMP_CONST(
    EMPNO       NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME       VARCHAR(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB         VARCHAR(9),
    TEL         VARCHAR(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE    DATE,
    SAL         NUMBER(7, 2) CONSTRAINT EMPCONST_SAL_CHK CHECK(SAL BETWEEN 1000 AND 9999),
    COMM        NUMBER(7, 2),
    DEPTNO      NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
);

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME IN('EMP_CONST', 'DEPT_CONST');