--
-- UNIQUE
-- 데이터 베이스에 저장할 데이터의 중복을 허용하지 않는 제약조건

-- 테이블 생성시에 UNIQUE 지정하기
CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID        VARCHAR2(20) UNIQUE,
    LOGIN_PWD       VARCHAR2(20) NOT NULL,
    TEL             VARCHAR2(20)
);

-- 제약조건 확인하기
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_UNIQUE';
 
-- 데이터 입력하기
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
     VALUES('TEST_ID_01', 'PWD01', '010-1234-1234');
     
-- LOGIN_ID에 중복된 데이터 입력해 보기
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
     VALUES('TEST_ID_01', 'PWD01', '010-1234-1234');
     
-- LOGIN_ID에 중복되지 않은 값으로 데이터 입력하기
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
     VALUES('TEST_ID_02', 'PWD01', '010-1234-1234');
     
-- UNIQUE 제약조건이 지정된 열에 NULL값으로 데이터 저장해 보기
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
     VALUES(NULL, 'PWD01', '010-1234-1234');
     
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
     VALUES(NULL, 'PWD01', '010-1234-1234');
-- UNIQUE 제약조건에는 NULL값이 중복되는것은 무관하다.

-- UPDATE문으로 UNIQUE 제약조건 열에 중복된 데이터 입력해 보기
UPDATE TABLE_UNIQUE
   SET LOGIN_ID = 'TEST_ID_01'
 WHERE LOGIN_ID IS NULL;
-- UNIQUE 제약조건에 의해 UPDATE역시 중복값으로 실행할 수 없다.


--
-- 테이블을 생성하며 UNIQUE 제약조건의 이름 지정하기
CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID        VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID UNIQUE,
    LOGIN_PWD       VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
    TEL             VARCHAR2(20)
);

-- 생성한 테이블의 제약조건 조회하기
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_UNIQUE2';


-- 이미 생성된 테이블의 제약조건 수정하기
ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE);
-- TEL 열에 중복된 데이터가 이미 있기 때문에 제약조건 수정 불가

-- TEL 열의 값을 NULL로 수정하기
UPDATE TABLE_UNIQUE
   SET TEL = NULL;

-- 다시 TEL열에 UNIQUE 제약조건으로 수정하기
ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE);

-- 수정 후, 제약조건 뷰 조회하기
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_UNIQUE';
 

-- 제약조건 이름 변경하기
ALTER TABLE TABLE_UNIQUE2
MODIFY(TEL CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE);

-- 제약조건 이름 변경 후, 제약조건 뷰 조회하기
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
 
 
-- 지정된 제약조건 삭제하기
ALTER TABLE TABLE_UNIQUE2
 DROP CONSTRAINT TBLUNQ_TEL_UNQ;
 
-- 제약조건 삭제 후, 제약조건 뷰 조회하기
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'TABLE_UNIQUE2';